language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"

matrix:
  allow_failures:
    - php: hhvm

addons:
  code_climate:
    repo_token: ea021e347f9f07cb8b3494ba29c3881962c423a063f6c99cf6e791ddbd7978b4

install:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phing build

after_script:
  - vendor/bin/coveralls -v
  - vendor/bin/test-reporter
