language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  
install: composer install --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration phpunit.xml.dist

after_script:
  - vendor/bin/coveralls -v